import { Barlow } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/sidebar/Sidebar";
const roboto = Barlow({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>

        <div className="min-h-screen flex flex-col bg-gray-100">
          <Navbar />
          <div className="flex flex-1">

            <Sidebar />

            <div className="flex-1 p-6">
              {children}
            </div>
          </div>

        </div>

      </body>
    </html>
  );
}
